services:
  - type: web
    name: fastframe-final
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: FASTFRAME_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: FF_USER
        sync: false
      - key: FF_PASS
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false