-- Frame Studio Digital: schema Postgres/Supabase
-- Execute este script no SQL Editor do Supabase.

BEGIN;

CREATE TABLE IF NOT EXISTS stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT REFERENCES stores(id),
    username TEXT NOT NULL UNIQUE,
    display_name TEXT,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('admin', 'user')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at TEXT,
    login_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT REFERENCES users(id),
    store_id BIGINT REFERENCES stores(id),
    nome TEXT NOT NULL,
    telefone TEXT,
    status TEXT NOT NULL DEFAULT 'novo',
    observacoes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS consultas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT REFERENCES users(id),
    store_id BIGINT REFERENCES stores(id),
    cliente_id BIGINT NOT NULL REFERENCES clientes(id),
    contexto TEXT,
    status TEXT NOT NULL DEFAULT 'em andamento',
    data_orcamento TEXT,
    validade TEXT,
    preco DOUBLE PRECISION NOT NULL DEFAULT 0,
    desconto DOUBLE PRECISION NOT NULL DEFAULT 0,
    total DOUBLE PRECISION NOT NULL DEFAULT 0,
    detalhes TEXT,
    observacoes TEXT,
    pagamentos_json JSONB,
    config_json JSONB,
    imagem_preview TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS store_state (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL REFERENCES stores(id),
    scope TEXT NOT NULL CHECK (scope IN ('catalog', 'rooms')),
    data_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (store_id, scope)
);

CREATE TABLE IF NOT EXISTS frames_cache (
    id TEXT PRIMARY KEY,
    store_id BIGINT NOT NULL REFERENCES stores(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    image_b64 TEXT NOT NULL,
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_stores_name ON stores(name);
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_store ON users(store_id);
CREATE INDEX IF NOT EXISTS idx_clientes_nome ON clientes(nome);
CREATE INDEX IF NOT EXISTS idx_clientes_telefone ON clientes(telefone);
CREATE INDEX IF NOT EXISTS idx_clientes_owner ON clientes(owner_user_id);
CREATE INDEX IF NOT EXISTS idx_clientes_store ON clientes(store_id);
CREATE INDEX IF NOT EXISTS idx_consultas_cliente ON consultas(cliente_id);
CREATE INDEX IF NOT EXISTS idx_consultas_data ON consultas(created_at);
CREATE INDEX IF NOT EXISTS idx_consultas_owner ON consultas(owner_user_id);
CREATE INDEX IF NOT EXISTS idx_consultas_store ON consultas(store_id);
CREATE INDEX IF NOT EXISTS idx_store_state_store_scope ON store_state(store_id, scope);
CREATE INDEX IF NOT EXISTS idx_frames_store_time ON frames_cache(store_id, created_at);

COMMIT;
